### PR TITLE
[WIP]: Modify text on the homepage

### PR DESCRIPTION
**Pull request by Eleonore9**
BEFORE
embed-before

CHANGES: 
The extra text changes the look of it a bit
embed-changes-4

### CODE REVIEW

**Comment by otfrom** [comment]
Can you paste in a screenshot of the change pls?

**Comment by Eleonore9** [comment]
@otfrom: ok. Compiling my last change and then I'll take a screenshot!

**Comment by otfrom** [comment]
lgtm, but @jasebell knows the requirement better

**Comment by jasebell** [comment]
The only change is please remove ‘welcome to the new embed site’. Then this is good to :shipit:

**Comment by jasebell** [comment]
:shipit:

**Pull request merged**
